### ISSUE TITLE
Add `ipympl` to NERSC Jupyter environments to improve image viewing.

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/desc-python#13]
@heather999 Could you kindly add ipympl to the next round of NERSC Jupyter kernel builds? This will bring us some more advance options and support from lsst.afw.display than available through the basic matplotlib interface.

I suppose this only needs to added to the desc-stack build, but I would suggest adding it to both desc-stack and desc-python for simplicitly (for both maintainer and user).

**Comment by heather999** [comment]
This is now included in the newly released `desc-stack` and `desc-python` jupyter kernels.  Just out of curiosity, is this something DM might add to their conda environment in the future?

**Comment by athornton** [comment]
I will look into incorporating ipympl into the Notebook Aspect of the LSST Science Platform.  It can be part of my ticket https://jira.lsstcorp.org/browse/DM-19686 .
