### ISSUE TITLE
Construct a complete list of packages for desc-python conda env

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-python#25]
As discussed at a recent CO meeting and following up on #desc-pipelines, this issue is an attempt to construct a new list of python packages generally useful for DESC users which does not depend on a DMstack environment. Up to now, we have based the `desc-python` environment on [DM's list](https://github.com/lsst/scipipe_conda_env/blob/master/etc/conda3_packages-linux-64.yml). We would now prefer to drop that and construct our own DESC conda environment from scratch. DESC users should review what we currently include, and add requests for additional packages on this GitHub issue.

Currently, we add the following to `desc-python` based on previous requests from DESC users:

- bokeh
- camb
- CatalogMatcher
- CCL
- corner
- dask 
- dask.distributed
- datashader
- descqa
- desc-dc2-dm-data
- emcee
- extinction (for sncosmo)
- fast3tree
- fastparquet
- fftw
- FoFCatalogMatching
- fitsio 
- GCR
- gcr-catalogs
-  google-cloud-bigquery
- gsl
- healpy
- helpers
- holoviews
- ipympl
- ipywidgets
- jupyter
- markupsafe
- NaMaster
- nose
- pandas
- parsl 
- psycopg2 
- pyarrow
- pymssql
- seaborn
- scikit-image
- scikit-learn
- Stile
- tables
- TreeCorr   
  
Packages that likely should be included
- astropy
- fits2hdf
- matplotlib
- numba
- numpy
- pytest
- scipy

Other packages mentioned, but not yet requested
- halotools
- sacc

**Comment by heather999** [comment]
I took a look at the conda env currently installed at CC: ` /pbs/throng/lsst/software/desc/anaconda3`, some packages popped out, but this is not an exhaustive list:

- boost-cpp
- esutil
- fftw
- sphinx
- swig

**Comment by rmjarvis** [comment]
I'll add:
* eigen
* lsstdesc-coord
* galsim
* astroplan

**Comment by elisachisari** [comment]
I imagine SACC will be requested soon, we've been using it a lot at Sprint Week. It would be great if you could add it.

**Comment by heather999** [comment]
Just added SACC to the existing desc-python env at NERSC.

**Comment by heather999** [comment]
Adding graphviz as requested by Bruno: https://pypi.org/project/graphviz/

**Comment by heather999** [comment]
With the latest desc-python release, I'll take the list we have as a first pass.  If anyone has additional requests, please open a new issue.
