### ISSUE TITLE
Set environment variable DESC_GCR_SITE to "nersc"

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/desc-python#39]
GCRCatalogs now uses site name to determine the appropriate root directory path. However, in batch nodes, site name cannot be determined by socket information (see discussion in https://github.com/LSSTDESC/gcr-catalogs/issues/438#issuecomment-630524503). Hence, it'd be useful to set an environment variable `DESC_GCR_SITE` to "nersc" in our python environments. GCRCatalogs will then this variable to determine the site it's running on.

**Comment by heather999** [comment]
Done
