### ISSUE TITLE
update the desc-pyspark kernel with latest Spark version (3.0.0)

### ISSUE THREAD

**Issue by JulienPeloton** [LSSTDESC/desc-python#51]
With recent upgrades, Java 8 is no more available on Cori and it has been replaced by Java 11. Unfortunately, the current installed version of Spark (2.4.4) does not support Java 11.

Action item: install Spark 3.0.0 for users, and update accordingly the desc-pyspark kernel.

NB: NERSC provides an alternative using Shifter (https://docs.nersc.gov/services/jupyter/#spark-on-jupyter) but such a kernel does not work (for me at least).

**Comment by heather999** [comment]
Also wondering about NERSC's shifter image, I see their [documentation](https://docs.nersc.gov/services/jupyter/#spark-on-jupyter) mentions `nersc/spark-2.3.0:v1` and I couldn't quickly get that working either.
but there is also a newer `nersc/spark-2.4.4:v1` image available.

**Comment by JulienPeloton** [comment]
I tried both shifter images without success so far :-(

**Comment by heather999** [comment]
Closing this.. I'm not sure what any future plans are for the desc-pyspark version of the environment.
