### ISSUE TITLE
pyarrow has been updated in desc-python, revisit desc-pyspark instructions

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-python#53]
pyarrow has now been updated to 0.17.1 in desc-python
concerning the updates in: https://github.com/LSSTDESC/desc-python/pull/52
I think it's no longer necessary for users to install their own copy of pyarrow - correct @JulienPeloton ?  Should we modify the instructions?

**Comment by JulienPeloton** [comment]
Thanks @heather999, I tried with the pyarrow version 0.17.1 in desc-python, but unfortunately I am hitting performance issues. An example as simple as

```python
# using spark 3.0
from pyspark.sql.functions import pandas_udf , PandasUDFType
import pandas as pd
import numpy as np

@pandas_udf('double')
def f(a: pd.Series, b: pd.Series) -> pd.Series:
    return a + b

# Create dummy DataFrame
colnames = ["a", "b"]
df = spark.sparkContext.parallelize(
    zip(
        [1.0, 2.0, 3.0, 4.0],
        [2.0, 2.0, 3.0, 4.0]
    )
).toDF(colnames)

# Add a and b columns
df.withColumn('a+b', f('a', 'b')).show()
```

never finishes. It is not crashing (no error thrown), but it takes forever to complete. For reference, I tried this example successfully (i.e. completed in millisecond) with many pyarrow versions (0.15+) installed locally at NERSC (`pip install pyarrow==0.XX.YY --user`), and I tried this snippet with pyarrow version 0.17.1 successfully on other platforms. 

So I suspect a pyarrow installation error in desc-python. Are other pyarrow users (@wmwv ?) seeing also performance issues with this new version?

**Comment by heather999** [comment]
bah!  Ok - I can look to downgrade pyarrow to something around 0.15.  It would be helpful to confirm others are having similar issues.  I will hold off on this given the scheduled tutorials for today and look into doing this overnight when less people are potentially running with `desc-python`

**Comment by JulienPeloton** [comment]
Downgrading could work, but I am not sure it is first thing we should try as I managed to run things correctly using pyarrow 0.17.1 (including at NERSC). So far, only the version in desc-python is causing trouble (to me at least). If others have similar issues, that would help.

How this version of pyarrow was installed? Were dependencies updated accordingly or do you freeze dependency versions? Could you try a re-installation?

**Comment by heather999** [comment]
This particular upgrade of `desc-python` was a complete re-install using conda-forge as the preferred channel - where I'm not pinning any packages.   So we picked up the latest pyarrow and any dependencies.  I'm trying to find a list of pyarrow dependencies - do you know of any in particular that might cause a problem?
I could try a separate install in another area - maybe as `desc-python-dev` so we can try it out.

**Comment by JulienPeloton** [comment]
This is a good idea to keep it separated in another area to experiment without causing perturbations to the current `desc-python`. I do not know of any dependency in particular which could cause the problem, but if you have the list of dependencies with versions, I can dig it out.

**Comment by heather999** [comment]
Here's what I can find from the installation of pyarrow 0.17.1 in the current `desc-python`
```
more /global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v2/pkgs/pyarrow-0.17.1-py37h1234567_10_cpu/info/index.json 
{
  "arch": "x86_64",
  "build": "py37h1234567_10_cpu",
  "build_number": 10,
  "constrains": [
    "arrow-cpp-proc * cpu"
  ],
  "depends": [
    "arrow-cpp 0.17.1 py37h1234567_10_cpu",
    "boost-cpp >=1.72.0,<1.72.1.0a0",
    "glog",
    "libgcc-ng >=7.5.0",
    "libstdcxx-ng >=7.5.0",
    "numpy >=1.16,<2.0a0",
    "pandas",
    "parquet-cpp 1.5.1.*",
    "python >=3.7,<3.8.0a0",
    "python_abi 3.7.* *_cp37m",
    "six"
  ],
  "license": "Apache-2.0",
  "name": "pyarrow",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1594031699206,
  "version": "0.17.1"
}
```

and looking back to the old one
```
more /global/common/software/lsst/common/miniconda/py3.7-4.7.12.1-v1/pkgs/pyarrow-0.13.0-py37h8b68381_2/info/index.json 
{
  "arch": "x86_64",
  "build": "py37h8b68381_2",
  "build_number": 2,
  "depends": [
    "arrow-cpp >=0.13.0,<0.14.0a0",
    "arrow-cpp >=0.13.0,<1.0a0",
    "boost-cpp >=1.70.0,<1.70.1.0a0",
    "libgcc-ng >=7.3.0",
    "libstdcxx-ng >=7.3.0",
    "numpy >=1.14,<2.0a0",
    "pandas",
    "parquet-cpp 1.5.1.*",
    "python >=3.7,<3.8.0a0",
    "six"
  ],
  "license": "Apache 2.0",
  "name": "pyarrow",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1560336773492,
  "version": "0.13.0"
}
```

There are certainly differences.. I guess I'll try an new install into desc-python-dev and pin pyarrow to 0.15.1 to see what we have.

**Comment by heather999** [comment]
I installed a desc-python-dev from scratch, which includes pyarrow 0.15.1 rather than 0.17.1.  I modified my local desc-pyspark kernel to use the latest desc-pyspark.sh and pointed to `desc-python-dev` , that works using the code snippet you provided above with the result:
```
+---+---+---+
|  a|  b|a+b|
+---+---+---+
|1.0|2.0|3.0|
|2.0|2.0|4.0|
|3.0|3.0|6.0|
|4.0|4.0|8.0|
+---+---+---+

```

If I go back to desc-python and pyarrow 0.17.1, I see the same behavior you report @JulienPeloton .  Looking in my $HOME/.jupyter.log, I see, some warnings at the code never finishes:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/gl
obal/u1/p/peloton/myspark/spark-3.0.0-bin-hadoop2.7/jars/spark-unsafe_2.12-3.0.0
.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.u
nsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect
ive access operations
WARNING: All illegal access operations will be denied in a future release
Ivy Default Cache set to: /global/homes/h/heatherk/.ivy2/cache
The jars for the packages stored in: /global/homes/h/heatherk/.ivy2/jars
:: loading settings :: url = jar:file:/global/u1/p/peloton/myspark/spark-3.0.0-b
in-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.github.astrolabsoftware#spark-fits_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-fdf3de70-3243-
48df-8859-cf08a319542b;1.0
	confs: [default]
	found com.github.astrolabsoftware#spark-fits_2.11;0.8.4 in central
:: resolution report :: resolve 316ms :: artifacts dl 4ms
	:: modules in use:
	com.github.astrolabsoftware#spark-fits_2.11;0.8.4 from central in [defau
lt]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   0   |   0   |   0   ||   1   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-fdf3de70-3243-48df-8859-cf
08a319542b
	confs: [default]
	0 artifacts copied, 1 already retrieved (0kB/10ms)
20/07/21 08:45:56 WARN NativeCodeLoader: Unable to load native-hadoop library fo
r your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLeve
l(newLevel).
[I 2020-07-21 08:45:59.593 SingleUserNotebookApp log:174] 200 GET /user/heatherk
/cori-shared-node-cpu/api/sessions?1595346359512 (heatherk@::ffff:10.42.156.54) 
4.43ms
````



I see the same behavior that you report @JulienPeloton in a notebook with the code snippet you included above.  Looking in my $HOME/.jupyter.log, I see:

```
/global/homes/p/peloton/myspark/spark-2.4.0-bin-hadoop2.7/bin/spark-class: line 71: /opt/java/jdk1.8.0_51/bin/java: No such file or directory
[IPKernelApp] WARNING | Unknown error in handling PYTHONSTARTUP file /global/homes/p/peloton/myspark/spark-2.4.0-bin-hadoop2.7/python/pyspark/shell.py:
[I 2020-07-21 08:22:12.283 SingleUserNotebookApp log:174] 200 GET /user/heatherk/cori-shared-node-cpu/api/contents/global/homes/h/heatherk?content=0&1595344932190 (heatherk@::ffff:10.42.156.54) 3.04ms
```

Do we want to point desc-pyspark at desc-python-dev for now and then see if this issue can be fixed so we can use `desc-python`?

**Comment by JulienPeloton** [comment]
Thanks @heather999 for trying the change! Unfortunately, changing to `desc-python-dev` does not solve the issue on my side, I still get stuck. More specifically I changed this line in the new kernel:

```diff
- source ${LSSTCONDA}/kernels/python.sh
+ source ${LSSTCONDA}/kernels/python-dev.sh
```

I will continue to investigate and keep you posted on this (fortunately I have a workaround by installing pyarrow locally to keep working in the meantime).

For the warnings, they are not a good sign but it seems unrelated ([JIRA link](https://issues.apache.org/jira/browse/SPARK-27981?focusedCommentId=16951625&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16951625)).

**Comment by heather999** [comment]
I had to change one more thing in my local copy of the kernel start up script:
`LSSTCONDABIN="${LSSTCONDA}/dev/envs/desc/bin"`

**Comment by JulienPeloton** [comment]
Oh great - it works with the additional modification you've done (with `desc-python-dev`)! Well done :-)

So I will open a PR with these modifications, and remove the instructions concerning local installation of pyarrow. I will continue to investigate the odd behaviour with `desc-python` separately.

**Comment by heather999** [comment]
Ok - Thanks @JulienPeloton! I updated the kernels at NERSC and the new version of desc-pyspark should be all set. Pending the cause of the problem with pyarrow 0.17.1 and desc-python, I can look at downgrading desc-python once the collaboration meeting is over.  I just want to keep things stable while any tutorials might be going on.

**Comment by heather999** [comment]
Closing!
