### ISSUE TITLE
review choice of OS for images

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/desc-python#91]
Using Centos7, but it's probably time to consider something leaner and to remove unnecessary software packages

**Comment by cwwalter** [comment]
Removing unnecessary sounds fine.  But, I think using the Rubin DM reference platform (I believe currently centos 7) seems like a good idea.

+ you don't have to spend any effort deciding :)

**Comment by heather999** [comment]
I think it depends on whether we're talking about `desc-python` or `desc-stack`.  For a stack enabled environment I see the benefit of staying in lock-step with DM, which I do think is centos 7.  For `desc-python` which is completely stack-free, I'm not so sure.  It would be nice to consider a leaner OS set up for the containers in this case.  At the very least, I'm fairly certain there is no need to attempt to completely replicate the OS libraries that DM pulls in for the stack.

**Comment by johannct** [comment]
What is the rationale to look for a leaner baseline distribution? Are there reports of inefficiencies, is the resulting container too big? Dealing with only one distribution at a time, whether stack or not, sounds like a good idea to me, unless we are forced otherwise.

**Comment by heather999** [comment]
The reasoning to initially use Centos 7 was driven by building a LSST Sci Pipelines environment, the notion of a stack-free env came later. If you go back into DESC history, you may even realize that initially we were using OpenSuse as it is close to the NERSC OS. There are many reasons to choose a base environment or even to consider supporting multiple base OSes or multiple "types" of images based on use-case, in no particular order:
* Container sizes - We are undoubtedly going to be adding more packages.
* Use cases - are we developing against this code or just running?  Do we need to support a development version that is perhaps not so lean?
* Performance
* Long Term Support
* Potential compatibility with host OS

Centos 7 EOL is 2024. Even though Rubin DM is using Centos 7 for the foreseeable future - we are not bound by that decision - especially for an environment that is not meant to run the LSST Science Pipelines. This is a request to take the time to actively consider what we want.  If I were to advocate for alternatives, I'd look at Ubuntu 20.04 LTS.  As an example, I believe the [TXPipe docker images are based on Ubuntu 18.04](https://github.com/joezuntz/txpipe-docker/blob/master/txpipe-base/Dockerfile).

**Comment by heather999** [comment]
closing.. desc-python has moved to ubuntu for its docker images. We can revisit this at some point if there is interest.
